# generatorOptions:
#   disableNameSuffixHash: true 
# configMapGenerator:
# - name: dummy-dev-postgres-backup
#   namespace: air
#   literals:
#   - PGPASSWORD=touring
#   - S3_DOMAIN=http://minio.air:9000
#   - S3_ACCESS_KEY=minioadmin
#   - S3_SECRET_KEY=minioadmin
